name: compile with mvn
on: [push]
env:
  DEPENDENCY_REPOSITORY: "robertopfe/demo-model"
  DEPENDENCY_PATH: "demo-model"
  DEPENDENCY_REF: "feature/prueba"
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          
        
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
          
        - name: Checkout cross repo
          uses: actions/checkout@v2
          with:
            repository:  ${{env.DEPENDENCY_REPOSITORY}}
            path:  ${{env.DEPENDENCY_PATH}}
            ref:  ${{env.DEPENDENCY_REF}}
        
        - name: Build with Maven
          working-directory: ./demo-model
          run: |
            mvn -B install --file pom.xml
        
        - name: ls
          working-directory: /home/runner/.m2/repository/com/inditex/example/demo-model/0.0.2
          run: |
            ls -la
            
        - name: Build with Maven
          run: mvn package
