name: compile with mvn
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-lastest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
        - name: Build with Maven
            run: mvn -B package --file pom.xml