name: compile with mvn
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11

        - name: Checkout cross repo
          uses: actions/checkout@v2
          with:
            repository:  robertopfe/demo-model
            path: demo-model

        - name: Build with Maven
          run: ls -la

        - name: Build with Maven
          run: cd /home/runner/work/demo/demo/demo-model | pwd | ls -la | mvn -B package --file pom.xml

        - uses: actions/checkout@v2

        - name: Build with Maven
          run: mvn -B package --file pom.xml