name: compile2 with mvn
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          

        - id: set_var
          run: |
            content=`cat ./dependencies.json`
            echo "::set-output name=jsonDep::$content"

        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
          
        - name: Checkout cross repo
          uses: actions/checkout@v2
          with:
            repository:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].repository}}
            path:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}
            ref:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].ref}}
        
        - name: Build with Maven
          working-directory: ./${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}
          run: |
            mvn -B install --file pom.xml
        
        - name: ls
          working-directory: /home/runner/.m2/repository/com/inditex/example/${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}/0.0.2
          run: |
            ls -la
            
        - name: ls 2
          working-directory: ./${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}/src/main/java/com/inditex/example/demomodel/entity
          run: |
            ls -la
            
        - name: Build with Maven
          run: mvn package
