name: External JSON - Compile with other repo dependency
on: [push]
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with: 
            path: ./principal

        - id: set_var
          working-directory: ./principal
          run: |
            content=`cat ./dependencies.json`
            echo "::set-output name=jsonDep::$content"

        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
          
        - name: Checkout cross repo
          uses: actions/checkout@v2
          with:
            repository:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].repository}}
            path:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}
            ref:  ${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].ref}}
        
        - name: Build with Maven
          working-directory: ./${{fromJson(steps.set_var.outputs.jsonDep).dependencies[0].path}}
          run: |
            mvn -B install --file pom.xml
            
        - name: Build with Maven
          working-directory: ./principal
          run: mvn package
