name: compile with mvn
on: [push]
env:
  DEPENDENCY_REPOSITORY: "robertopfe/demo-model"
  DEPENDENCY_PATH: "demo-model"
  DEPENDENCY_REF: "feature/prueba"
jobs:
  compile-mvn:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2          
        
        - name: Set up JDK 1.11
          uses: actions/setup-java@v1
          with:
            java-version: 1.11
          
        - name: Checkout cross repo
          uses: actions/checkout@v2
          with:
            repository:  ${{env.DEPENDENCY_REPOSITORY}}
            path:  ${{env.DEPENDENCY_PATH}}
            ref:  ${{env.DEPENDENCY_REF}}


        - name: Setup Maven Cache
          uses: actions/cache@v2.1.6
          continue-on-error: true
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
              
            
        - name: Build with Maven repo demo-model
          working-directory: ./demo-model
          run: |
            mvn -B install --file pom.xml
        
        - name: ls ./demo-model/target/classes/com/inditex/example/demomodel/entity
          working-directory: ./demo-model/target/classes/com/inditex/example/demomodel/entity
          run: |
            ls -la 
            cat ProductEntity.class
            
        - name: ls /home/runner/.m2/repository/com/inditex/example/demo-model/0.0.2
          working-directory: /home/runner/.m2/repository/com/inditex/example/demo-model/0.0.2
          run: |
            ls -la
            
        - name: Build with Maven repo demo
          run: mvn package
